# Example Secret for PostgreSQL
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
stringData:
  POSTGRES_DB: thanhho_coffeeshop
  POSTGRES_USER: thanhho_admin
  POSTGRES_PASSWORD: thanhho_secret
  PG_URL: postgres://thanhho_admin:thanhho_secret@thanhho-db.coffeeshop-aws.com:5432/thanhho_coffeeshop?sslmode=disable
  PG_DSN_URL: host=thanhho-db.coffeeshop-aws.com user=thanhho_admin password=thanhho_secret dbname=thanhho_coffeeshop sslmode=disable
---
# Example Secret for RabbitMQ
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
stringData:
  RABBITMQ_DEFAULT_USER: thanhho_rmq
  RABBITMQ_DEFAULT_PASS: thanhho_rmq_secret
  RABBITMQ_URL: amqp://thanhho_rmq:thanhho_rmq_secret@thanhho-rmq.coffeeshop-aws.com:5672/
